src/Entity/Commande.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use App\Entity\Facture;
use App\Entity\Utilisateur;
use App\Entity\CommandeDetail;
use Doctrine\DBAL\Types\Types;

use Doctrine\ORM\Mapping as ORM;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\Collection;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: CommandeRepository::class)]
#[ApiResource]


class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?DateTimeImmutable $date_commande = null;

    

    #[ORM\ManyToOne(inversedBy: 'commandes', targetEntity: Utilisateur::class, cascade: ['persist'])]
    private ?utilisateur $utilisateur = null;

    #[ORM\OneToMany(mappedBy: 'com', targetEntity: CommandeDetail::class, cascade: ['persist'])]
    private Collection $commandeDetails;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse_fact = null;

    #[ORM\Column(length: 255)]
    private ?string $commentaire = null;

    #[ORM\OneToMany(mappedBy: 'com_id', targetEntity: Facture::class)]
    private Collection $Commande;

    // #[ORM\OneToMany(mappedBy: 'adresse1', targetEntity: Facture::class)]
    // private Collection $factures;

   

    public function __construct()
    {
        $this->commandeDetails = new ArrayCollection();
        $this->date_commande= new  DateTimeImmutable( );
        // $this->factures = new ArrayCollection();
        $this->Commande = new ArrayCollection();
        
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCommande(): ?\DateTimeImmutable
    {
        return $this->date_commande;
    }

    #[ORM\PrePersist]
    public function setDateCommande(): self
    {
        $this->date_commande = new \DateTimeImmutable();

        return $this;
    }

    public function __toString()
    {
        return $this->date_commande;
    }
    

    public function getUtilisateur(): ?utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection<int, CommandeDetail>
     */
    public function getCommandeDetails(): Collection
    {
        return $this->commandeDetails;
    }

    public function addCommandeDetail(CommandeDetail $commandeDetail): ?static
    {
        if (!$this->commandeDetails->contains($commandeDetail)) {
            $this->commandeDetails->add($commandeDetail);
            $commandeDetail->setCom($this);
        }

        return $this;
    }

    public function removeCommandeDetail(CommandeDetail $commandeDetail): ?static
    {
        if ($this->commandeDetails->removeElement($commandeDetail)) {
            // set the owning side to null (unless already changed)
            if ($commandeDetail->getCom() === $this) {
                $commandeDetail->setCom(null);
            }
        }

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): ?static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getAdresseFact(): ?string
    {
        return $this->adresse_fact;
    }

    public function setAdresseFact(string $adresse_fact): ?static
    {
        $this->adresse_fact = $adresse_fact;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): ?static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    // /**
    //  * @return Collection<int, Facture>
    //  */
    // public function getFactures(): Collection
    // {
    //     return $this->factures;
    // }

    // public function addFacture(Facture $facture): ?static
    // {
    //     if (!$this->factures->contains($facture)) {
    //         $this->factures->add($facture);
    //         $facture->setAdresse1($this);
    //     }

    //     return $this;
    // }

    // public function removeFacture(Facture $facture): ?static
    // {
    //     if ($this->factures->removeElement($facture)) {
    //         // set the owning side to null (unless already changed)
    //         if ($facture->getAdresse1() === $this) {
    //             $facture->setAdresse1(null);
    //         }
    //     }

    //     return $this;
    // }

    /**
     * @return Collection<int, Facture>
     */
    public function getCommande(): Collection
    {
        return $this->Commande;
    }

    public function addCommande(Facture $commande): static
    {
        if (!$this->Commande->contains($commande)) {
            $this->Commande->add($commande);
            $commande->setComId($this);
        }

        return $this;
    }

    public function removeCommande(Facture $commande): static
    {
        if ($this->Commande->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getComId() === $this) {
                $commande->setComId(null);
            }
        }

        return $this;
    }

   
}

src/Controller/CommandeCrudController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\Commande1Type;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/commande/crud')]
class CommandeCrudController extends AbstractController
{
    #[Route('/', name: 'app_commande_crud_index', methods: ['GET'])]
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande_crud/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    #[Route('/mesCommande/{id}', name: 'app_commande_mon_index', methods: ['GET'])]
    public function monIndex(CommandeRepository $commandeRepository, $id): Response
    {
    //     $x = $commandeRepository->findBy(['utilisateur' => $this->getUser()]);
    //     $y = $commandeRepository->myCommande();
    //     dd($y);
    //    // dd($x[2]->getId());
        return $this->render('commande_crud/mescommande.html.twig', [
            'commandes' => $commandeRepository->myCommande($id)
        ]);
    }
    #[Route('/facture/{id}', name: 'app_commande_mon_index', methods: ['GET'])]
    public function facture(CommandeRepository $commandeRepository, $id): Response
    {
    //     $x = $commandeRepository->findBy(['utilisateur' => $this->getUser()]);
    //     $y = $commandeRepository->myCommande();
    //     dd($y);
    //    // dd($x[2]->getId());
        return $this->render('commande_crud/facture.html.twig', [
            'commandes' => $commandeRepository->myCommande($id)
        ]);
    }

    #[Route('/new', name: 'app_commande_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commande = new Commande();
        $form = $this->createForm(Commande1Type::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commande);
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande_crud/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_crud_show', methods: ['GET'])]
    public function show(Commande $commande): Response
    {
        return $this->render('commande_crud/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commande_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Commande1Type::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande_crud/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_crud_delete', methods: ['POST'])]
    public function delete(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commande_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_commande_crud_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commande_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commande_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>

    {{ include('commande_crud/_delete_form.html.twig') }}
{% endblock %}

templates/commande_crud/facture.html.twig
 {% extends 'base.html.twig' %}

{% block title %}facturation facture{% endblock %} 

{% block body %}
   

   
   
    <table class="table">
        <thead>
            <tr>
                 <th colspan="6">n° commande</th>
                 <th >date</th>
                <th colspan="6">produits</th>
                <th colspan="6">prix</th>
                <th colspan="6">quantite</th>
                 <th colspan="6">adresse livraison</th> 
                 <th colspan="6">adresse_facturation</th> 
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}

                <td colspan="6">{{ commande.com_id }}</td>
               <td colspan="5">{{ commande.date|date("Y-m-d H:i:s") }}</td>
                <td colspan="6">{{ commande.p_nom }}</td>
                <td colspan="6">{{ commande.prix }}</td>
                 <td colspan="6">{{ commande.quantite }}</td>
                 <td colspan="6">{{ commande.adresse_livraison }}</td>
                 <td colspan="6">{{ commande.adresse_facturation }}</td>
                 
                  </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

     {# <a href="{{ path('app_commande_crud_show', {'id': .id}) }}">show</a> #}
 {% endblock %}  

templates/commande_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_commande</th>
                <th>Adresse</th>
                <th>Adresse_fact</th>
                <th>Commentaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.dateCommande ? commande.dateCommande|date(' Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.adresse }}</td>
                <td>{{ commande.adresseFact }}</td>
                <td>{{ commande.commentaire }}</td>
                <td>
                    <a href="{{ path('app_commande_crud_show', {'id': commande.id}) }}">show</a>
                    {# <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">edit</a> #}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_commande_crud_new') }}">Create new</a> #}
{% endblock %}

templates/commande_crud/mescommande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

   
   
    <table class="table">
        <thead>
            <tr>
                 <th>n° commande</th>
                 <th>date</th>
                <th>produits</th>
                <th>prix</th>
                <th>quantite</th>
                 <th>adresse livraison</th> 
                 <th>adresse_facturation</th> 
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.com_id }}</td>
               <td>{{ commande.date|date("Y-m-d H:i:s") }}</td>
                <td>{{ commande.p_nom }}</td>
                <td>{{ commande.prix }}</td>
                 <td>{{ commande.quantite }}</td>
                 <td>{{ commande.adresse_livraison }}</td>
                 <td>{{ commande.adresse_facturation }}</td>
                 
                 




                {# <td>{{ commande.dateCommande ? commande.dateCommande|date('Y-m-d') : '' }}</td>
                <td>{{ commande.adresse }}</td>
                <td>{{ commande.adresseFact }}</td>
                <td>{{ commande.commentaire }}</td> #}
                {# <td>
                    <a href="{{ path('app_commande_crud_show',{id: commande.com_id }) }}">show</a>
                    {# <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">edit</a> #}
                {# </td>  #}
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_commande_crud_new') }}">Create new</a> #}
{% endblock %}

templates/commande_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('commande_crud/_form.html.twig') }}

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>
{% endblock %}

templates/commande_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Date_commande</th>
                <td>{{ commande.dateCommande ? commande.dateCommande|date('Y-m-d') : '' }}</td>
            </tr>
            {# <tr>
              <th>prix</th>
            <td>{{ commande.prix }}</td>
            </tr> #}
            <tr>
                <th>Adresse</th>
                <td>{{ commande.adresse }}</td>
            </tr>
            <tr>
                <th>Adresse_fact</th>
                <td>{{ commande.adresseFact }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ commande.commentaire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>

    {# <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">edit</a> #}

    {{ include('commande_crud/_delete_form.html.twig') }}
{% endblock %}